# Generated by Django 4.1.7 on 2023-03-19 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_categories_blogpost_author_blogpost_created_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="summary",
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
