# Generated by Django 4.1.7 on 2023-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_blogpost_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost", name="slug", field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="summary",
            field=models.TextField(max_length=1000),
        ),
    ]
