# Generated by Django 4.1.7 on 2023-03-20 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_blogpost_slug_alter_blogpost_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="imageCaption",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="imageUrl",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
